#+title: [S]nake [O]il [S]oftware App

SoS is an insolent app meant for Software Development teams to be more effective
in creating good quality software.

It does so by bringing transparency in your team and by aiming to save you from
meetings.

Being an insolent software, you can start using it without waiting on anyone to
adopt it organization wide. Although to get most out of SoS, it is better if you
join along your team.

* MVP

SoS is in early stages of development. In its MVP form, it has following goals:

#+begin_quote
Replace daily standup meetings while enhancing its intended value
#+end_quote

It does so by allowing developers to update their team on:
   - What they are working on today
   - What they accomplished the previous working day
   - Any challenges and impediments they are facing for a particular task

* Development Setup

Follow this guide to setup an environment for developing SoS app

** Prerequisites

Following must be installed:
1. [[https://www.docker.com/][Docker]]
2. [[https://docs.docker.com/compose/][Docker Compose]]
3. [[https://hasura.io/docs/1.0/graphql/manual/hasura-cli/index.html#installation][Hasura CLI]]

** Setup

1. *Start the services*
  #+begin_src sh
  cd /path/to/humans-of-trantor
  docker-compose up
  #+end_src

2. Copy =.env= files

  #+begin_src sh
    # hasura/.env
    export HASURA_GRAPHQL_ADMIN_SECRET=myadminsupersecretkey
  #+end_src

  #+begin_src sh
    # sidecar/.env
    NODE_ENV="development"
    EXPRESS_SESSION_SECRET="EXPRESS_SESSION_SECRET"
    REDISCLOUD_SESSION_URL="redis://redis:6379"
    GRAPHQL_LOGGER=true
    HOSTNAME="localhost"
    SMTP_HOST="smtp.ethereal.email"
    SMTP_PORT="587"
    SMTP_USER="marcia.kirlin65@ethereal.email"
    SMTP_PASSWORD="EN2pw6VzAZnkyzAuDb"
    APP_NAME="SoS App"
  #+end_src

3. *Apply [[https://hasura.io/docs/1.0/graphql/manual/migrations/index.html][hasura migration]]*
   #+begin_src sh
     cd ./hasura
     source ./.env
     hasura migrate apply
   #+end_src

4. *Start hasura console*
  #+begin_src sh
    hasura console
  #+end_src
