module.exports = {
  arrowParens: "avoid",
  bracketSpacing: true,
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  printWidth: 100,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: true,
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false,
  doubleQuote: true,
  singleQuote: false,
};
