
alter table "public"."users" drop constraint "valid_avatar";
alter table "public"."users" drop constraint "valid_name";
alter table "public"."team_members" drop constraint "valid_ecode";
alter table "public"."projects" drop constraint "valid_logo_square";
alter table "public"."projects" add constraint "valid_logo_square" check (CHECK (length(name) < 200));
alter table "public"."projects" drop constraint "vaild_logo";
alter table "public"."projects" add constraint "vaild_logo" check (CHECK (length(name) < 200));
alter table "public"."organizations" drop constraint "valid_square_logo";
alter table "public"."organizations" add constraint "valid_square_logo" check (CHECK (length(name) < 200));
alter table "public"."organizations" drop constraint "valid_banner";
alter table "public"."organizations" add constraint "valid_banner" check (CHECK (length(name) < 200));
alter table "public"."employees" drop constraint "valid_headshot";
alter table "public"."employees" add constraint "valid_headshot" check (CHECK (length(name) < 200));
alter table "public"."employees" drop constraint "valid_email";
alter table "public"."employees" add constraint "valid_email" check (CHECK (length(name) < 200));
alter table "public"."employees" drop constraint "valid_ecode";
alter table "public"."employees" add constraint "valid_ecode" check (CHECK (length(name) < 200));
alter table "public"."teams" drop constraint "valid_logo";
alter table "public"."teams" add constraint "valid_logo" check (CHECK (length(name) < 200));
alter table "public"."teams" drop constraint "valid_logo_square";
alter table "public"."teams" drop constraint "valid_logo";
alter table "public"."teams" add constraint "valid_logo" check (CHECK (length(name) < 50));
alter table "public"."teams" drop constraint "valid_logo";
alter table "public"."teams" drop constraint "valid_name";
alter table "public"."projects" drop constraint "valid_name";
alter table "public"."projects" add constraint "valid_name" check (CHECK (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 50));
alter table "public"."projects" drop constraint "valid_logo_square";
alter table "public"."projects" drop constraint "vaild_logo";
alter table "public"."projects" drop constraint "valid_description";
alter table "public"."projects" add constraint "valid_description" check (CHECK (NULL::boolean OR btrim(description) <> ''::text AND length(description) > 10 AND length(description) < 200));
alter table "public"."organizations" drop constraint "valid_banner";
alter table "public"."organizations" drop constraint "valid_square_logo";
alter table "public"."employees" drop constraint "valid_ecode";
alter table "public"."employees" drop constraint "valid_email";
alter table "public"."employees" drop constraint "valid_headshot";
alter table "public"."organizations" drop constraint "valid_name";
alter table "public"."organizations" add constraint "valid_name" check (CHECK (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 50));
alter table "public"."projects" drop constraint "valid_description";
alter table "public"."projects" drop constraint "valid_name";
alter table "public"."organizations" drop constraint "valid_name";
alter table "public"."organizations" add constraint "valid_name" check (CHECK (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 200));
alter table "public"."employees" drop constraint "valid_name";