alter table "public"."employees" add constraint "valid_name" check (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 50);
alter table "public"."organizations" add constraint "valid_name" check (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 50);
alter table "public"."projects" add constraint "valid_name" check (btrim(name) <> ''::text AND length(name) > 2 AND length(name) < 50);
alter table "public"."projects" add constraint "valid_description" check ( null OR trim(description) <> ''::text AND length(description) > 10 AND length(description) < 200);
alter table "public"."organizations" drop constraint "valid_name";
alter table "public"."organizations" add constraint "valid_name" check (trim(name) <> ''::text AND length(name) > 2 AND length(name) < 50);
alter table "public"."employees" add constraint "valid_headshot" check (length(name) < 200);
alter table "public"."employees" add constraint "valid_email" check (length(name) < 200);
alter table "public"."employees" add constraint "valid_ecode" check (length(name) < 200);
alter table "public"."organizations" add constraint "valid_square_logo" check (length(name) < 200);
alter table "public"."organizations" add constraint "valid_banner" check (length(name) < 200);
alter table "public"."projects" drop constraint "valid_description";
alter table "public"."projects" add constraint "valid_description" check (NULL::boolean OR btrim(description) <> ''::text AND length(description) > 2 AND length(description) < 200);
alter table "public"."projects" add constraint "vaild_logo" check (length(name) < 200);
alter table "public"."projects" add constraint "valid_logo_square" check (length(name) < 200);
alter table "public"."projects" drop constraint "valid_name";
alter table "public"."projects" add constraint "valid_name" check (trim(name) != '' AND length(name) > 2 AND length(name) < 50);
alter table "public"."teams" add constraint "valid_name" check ( length(name) < 50);
alter table "public"."teams" add constraint "valid_logo" check (length(name) < 50);
alter table "public"."teams" drop constraint "valid_logo";
alter table "public"."teams" add constraint "valid_logo" check (length(name) < 200);
alter table "public"."teams" add constraint "valid_logo_square" check (length(logo_square) < 200);
alter table "public"."teams" drop constraint "valid_logo";
alter table "public"."teams" add constraint "valid_logo" check (length(logo) < 200);
alter table "public"."employees" drop constraint "valid_ecode";
alter table "public"."employees" add constraint "valid_ecode" check (length(ecode) < 200);
alter table "public"."employees" drop constraint "valid_email";
alter table "public"."employees" add constraint "valid_email" check (length(email) < 50);
alter table "public"."employees" drop constraint "valid_headshot";
alter table "public"."employees" add constraint "valid_headshot" check (length(headshot) < 200);
alter table "public"."organizations" drop constraint "valid_banner";
alter table "public"."organizations" add constraint "valid_banner" check (length(banner) < 200);
alter table "public"."organizations" drop constraint "valid_square_logo";
alter table "public"."organizations" add constraint "valid_square_logo" check (length(square_logo) < 200);
alter table "public"."projects" drop constraint "vaild_logo";
alter table "public"."projects" add constraint "vaild_logo" check (length(logo) < 200);
alter table "public"."projects" drop constraint "valid_logo_square";
alter table "public"."projects" add constraint "valid_logo_square" check (length(logo_square) < 200);
alter table "public"."team_members" add constraint "valid_ecode" check (trim(ecode) <> ''::text AND length(ecode) > 2 AND length(ecode) < 50);
alter table "public"."users" add constraint "valid_name" check ( trim(name) <> ''::text AND length(name) > 2 AND length(name) < 50);
alter table "public"."users" add constraint "valid_avatar" check (length(avatar) < 200);
